language: php

php:
  - 7.1

before_script:
 # Take our travis-ci environment variable and update coveralls config with our token
 - sed -ri 's/^COVERALLS_TOKEN/\$COVERALLS_TOKEN/' .coveralls.yml
 - composer install --prefer-source --no-interaction

script: vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v